### ISSUE TITLE
Clarify what this project is in the Read Me

### ISSUE THREAD

**Issue by bladeoflight16** [miniflycn/compass-node#12]
Is this a full Node.JS port of [Compass](http://compass-style.org/)? Or does it still depend on Ruby? Does it work with [node-sass](https://www.npmjs.com/package/node-sass)? (I guess it does since that's a dependency, but being explicit for people running across this tool would be nice.) Is there a command line interface? In short, the Read Me doesn't help me figure out if this is useful to me. Some statement of goals and future work might help as well.

I should mention that I'm basically filing this as an issue because you need to do this to advertise the library. My guess is that this *is* a full Node.js port of Compass, which is something that's badly needed, imo. Look at how node-sass advertises itself. The first sentence tells me this information. It's a Node.js wrapper around libsass, a stylesheet preprocessor. So I know immediately that if I want to use SASS but don't want to use Node instead of Ruby, this might be useful to me. Play this kind of info up in your Read Me. I think you'll find a **lot** of interest in your project if it's a full Node.js port of Compass.

**Comment by miniflycn** [comment]
I'm sorry for that. My English is very general, it may be difficult to express clearly.
Thanks for your help, and I will add it to Readme later.
