### ISSUE TITLE
Sprite: wrong mixin name generated

### ISSUE THREAD

**Issue by nkashyap** [miniflycn/compass-node#13]
Sprite should generate mixin with last folder name and also question about background url ?? (may be image-url() would be better)

http://compass-style.org/help/tutorials/spriting/

Nested Folders

**Note: The use of orange is only for this example, "orange" represents the folder name that contains your sprites.

Sprites stored in a nested folder will use the last folder name in the path as the sprite name.

Example:

  @import "themes/orange/*.png";
  @include all-orange-sprites;

**Comment by miniflycn** [comment]
Please see the test case:
https://github.com/miniflycn/compass-node/tree/master/test/sprite
